<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>EDH 7916 - I: Basic Statistical Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./apple-touch-icon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="site-attachments/styles.css">
<meta property="og:title" content="EDH 7916 - I: Basic Statistical Models">
<meta property="og:image" content="https://capaldi.info/7916/apple-touch-icon.png">
<meta property="og:site-name" content="EDH 7916">
<meta property="og:image:height" content="180">
<meta property="og:image:width" content="180">
<meta name="twitter:title" content="EDH 7916 - I: Basic Statistical Models">
<meta name="twitter:image" content="https://capaldi.info/7916/apple-touch-icon.png">
<meta name="twitter:image-height" content="180">
<meta name="twitter:image-width" content="180">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./12-Program-Stats.html">Programming</a></li><li class="breadcrumb-item"><a href="./12-Program-Stats.html">I: Basic Statistical Models</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">EDH 7916</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homepage</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-Syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Getting Started</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Setup-Installing-R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">I: Installing R &amp; RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Setup-Reading-Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">II: Reading Data &amp; IPEDS</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Extra-01-Setup-GitHub.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extra: Git &amp; GitHub</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Data Wrangling</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Data-Wrangling-I.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">I: Enter the tidyverse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Data-Wrangling-II.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">II: Appending, joining, &amp; reshaping data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-Data-Wrangling-III.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">III: Working with strings &amp; dates</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Data-Wrangling-IV.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">IV: Tidyverse Tricks &amp; SQL</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Data Visualization</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Data-Viz-I.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">I: Basics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-Data-Viz-II.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">II: Customization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-Data-Viz-III.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">III: Maps &amp; Spatial Data (Feat. APIs)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-Data-Viz-IV.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">IV: Interactive Graphics</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">Quarto</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reproducable Reports with Quarto</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Programming</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-Program-Stats.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">I: Basic Statistical Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-Program-Functional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">II: Functions &amp; Loops</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Extra-02-Program-Vanilla.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extra: Vanilla R (Data Wrangling I Redux)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">Philosophy of Data Wrangling</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-Bens-Philosophy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dr.&nbsp;Skinner’s Philosophy</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99-Final-Project.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Final Project</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">I: Basic Statistical Models</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">Lesson</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Assignment</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>After your data have been wrangled from raw values to an analysis data set and you’ve explored it with summary statistics and graphics, you are ready to model it and begin making inferences. As one should expect from a statistical language, R has a powerful system for fitting statistical and econometric models.</p>
<p>Because the purpose of this course is to learn and practice using a good quantitative work flow, we won’t spend time much time interpreting the results from our inferential models. Instead, this lesson will give you the basic understanding you need to run correlations and t-tests in R as well as give a quick overview of how to use survey weights. (We’ll cover regressions and predictions in a later lesson.) That said, the lessons you’ve learned in other courses about proper statistical practice still stand — this lesson should help you apply what you’ve learned before.</p>
<section id="data" class="level2">
<h2 data-anchor-id="data">Data</h2>
<p>In this lesson, we’ll use data from the <a href="https://nces.ed.gov/surveys/els2002/">NCES Education Longitudinal Study of 2002</a>. Much like HSLS, ELS is a nationally representative survey that initially surveyed students in their early high school career (10th grade in 2002) and followed them into college and the workforce. We’ll again use a smaller version of the data, so be sure to get the full data files if you decide to use ELS in a future project. One additional benefit of ELS is that the public use files contain the weights we’ll use to properly account for the survey design later in the lesson.</p>
<p>Here’s a codebook with descriptions of the variables included in our lesson today:</p>
<table class="table">
<colgroup>
<col style="width: 24%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">variable</th>
<th style="text-align: left;">description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">stu_id</td>
<td style="text-align: left;">student id</td>
</tr>
<tr class="even">
<td style="text-align: left;">sch_id</td>
<td style="text-align: left;">school id</td>
</tr>
<tr class="odd">
<td style="text-align: left;">strat_id</td>
<td style="text-align: left;">stratum</td>
</tr>
<tr class="even">
<td style="text-align: left;">psu</td>
<td style="text-align: left;">primary sampling unit</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bystuwt</td>
<td style="text-align: left;">student weight</td>
</tr>
<tr class="even">
<td style="text-align: left;">bysex</td>
<td style="text-align: left;">sex-composite</td>
</tr>
<tr class="odd">
<td style="text-align: left;">byrace</td>
<td style="text-align: left;">student’s race/ethnicity-composite</td>
</tr>
<tr class="even">
<td style="text-align: left;">bydob_p</td>
<td style="text-align: left;">student’s year and month of birth</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bypared</td>
<td style="text-align: left;">parents’ highest level of education</td>
</tr>
<tr class="even">
<td style="text-align: left;">bymothed</td>
<td style="text-align: left;">mother’s highest level of education-composite</td>
</tr>
<tr class="odd">
<td style="text-align: left;">byfathed</td>
<td style="text-align: left;">father’s highest level of education-composite</td>
</tr>
<tr class="even">
<td style="text-align: left;">byincome</td>
<td style="text-align: left;">total family income from all sources 2001-composite</td>
</tr>
<tr class="odd">
<td style="text-align: left;">byses1</td>
<td style="text-align: left;">socio-economic status composite, v.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">byses2</td>
<td style="text-align: left;">socio-economic status composite, v.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bystexp</td>
<td style="text-align: left;">how far in school student thinks will get-composite</td>
</tr>
<tr class="even">
<td style="text-align: left;">bynels2m</td>
<td style="text-align: left;">els-nels 1992 scale equated sophomore math score</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bynels2r</td>
<td style="text-align: left;">els-nels 1992 scale equated sophomore reading score</td>
</tr>
<tr class="even">
<td style="text-align: left;">f1qwt</td>
<td style="text-align: left;">questionnaire weight for f1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">f1pnlwt</td>
<td style="text-align: left;">panel weight, by and f1 (2002 and 2004)</td>
</tr>
<tr class="even">
<td style="text-align: left;">f1psepln</td>
<td style="text-align: left;">f1 post-secondary plans right after high school</td>
</tr>
<tr class="odd">
<td style="text-align: left;">f2ps1sec</td>
<td style="text-align: left;">Sector of first postsecondary institution</td>
</tr>
<tr class="even">
<td style="text-align: left;">female</td>
<td style="text-align: left;">== 1 if female</td>
</tr>
<tr class="odd">
<td style="text-align: left;">moth_ba</td>
<td style="text-align: left;">== 1 if mother has BA/BS</td>
</tr>
<tr class="even">
<td style="text-align: left;">fath_ba</td>
<td style="text-align: left;">== 1 if father has BA/BS</td>
</tr>
<tr class="odd">
<td style="text-align: left;">par_ba</td>
<td style="text-align: left;">== 1 if either parent has BA/BS</td>
</tr>
<tr class="even">
<td style="text-align: left;">plan_col_grad</td>
<td style="text-align: left;">== 1 if student plans to earn college degree</td>
</tr>
<tr class="odd">
<td style="text-align: left;">lowinc</td>
<td style="text-align: left;">== 1 if income &lt; $25k</td>
</tr>
</tbody>
</table>
<p>Let’s load the libraries and data!</p>
<p>…but first! You’ll most likely need to install the <a href="https://CRAN.R-project.org/package=survey"><code>survey</code> package</a> first, using <code>install.packages("survey")</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## ---------------------------</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="do">## libraries</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="do">## ---------------------------</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.0     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.1.8
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: grid
Loading required package: Matrix

Attaching package: 'Matrix'

The following objects are masked from 'package:tidyr':

    expand, pack, unpack

Loading required package: survival

Attaching package: 'survey'

The following object is masked from 'package:graphics':

    dotchart</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">## ---------------------------</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="do">## input data</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="do">## ---------------------------</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="do">## assume we're running this script from the ./scripts subdirectory</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="fu">file.path</span>(<span class="st">"data"</span>, <span class="st">"els_plans.dta"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="correlations" class="level2">
<h2 data-anchor-id="correlations">Correlations</h2>
<p>In prior lessons, we’ve visually checked for correlations between variables through plotting. We can also produce more formal tests of correlation using R’s <code>cor()</code> function. By default, it gives us the <a href="https://en.wikipedia.org/wiki/Pearson_correlation_coefficient">Pearson correlation coefficient</a>, though we can also use it to return other versions.</p>
<p>First, let’s check the correlation between math and reading scores. Because this is a base R function, we’ll need to use <code>df$</code> notation. We’ll also need to be explicit about removing missing values with the argument, <code>use = "complete.obs"</code> (one of the few annoying function options that doesn’t really match how other functions work).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="do">## correlation between math and reading scores</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(df<span class="sc">$</span>bynels2m, df<span class="sc">$</span>bynels2r, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7521538</code></pre>
</div>
</div>
<p>As we might have hypothesized, there is a strong positive correlation between math and reading scores.</p>
<p>We can also build a correlation matrix if we give <code>cor()</code> a data frame. Our data set, though smaller than the full ELS data set, is still rather large. We’ll only check the correlations between a few variables. In this next example, I’ll show you how you might do this using the tidyverse way we’ve used in other lessons.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="do">## correlation between various columns, using pipes</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="do">## select a few variables</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(byses1, bynels2m, bynels2r, par_ba) <span class="sc">%&gt;%</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="do">## use a . to be the placeholder for the piped in data.frame</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cor</span>(., <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            byses1  bynels2m  bynels2r    par_ba
byses1   1.0000000 0.4338441 0.4315718 0.7041740
bynels2m 0.4338441 1.0000000 0.7490148 0.2980608
bynels2r 0.4315718 0.7490148 1.0000000 0.2865717
par_ba   0.7041740 0.2980608 0.2865717 1.0000000</code></pre>
</div>
</div>
<p>Per our expectations, the main diagonal is all 1s — every variable is perfectly correlated with itself — and the mirror cells on either side of the line are the same: [2,1] == [1,2] because the correlation between <code>bynels2m</code> and <code>byses1</code> is the same as <code>byses1</code> and <code>bynels2m</code> (the order doesn’t matter).</p>
<blockquote class="blockquote">
<h4 id="quick-exercise">Quick exercise</h4>
<p>Run a correlation of both math and reading scores against whether the father has a Bachelor’s degree (<code>fath_ba</code>) or the mother has a Bachelor’s degree (<code>moth_ba</code>). In what ways, if any, is this different than what you get when using the combined <code>par_ba</code> indicator variable?</p>
</blockquote>
</section>
<section id="t-test" class="level2">
<h2 data-anchor-id="t-test">t-test</h2>
<p>One common statistical test is a t-test for a difference in means across groups (there are, of course, <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/t.test.html">other types of t-tests that R can compute</a>). This version of the test can be computed using the R formula syntax: <code>y ~ x</code>. In our example, we’ll compute base-year math scores against parent’s college education level. Notice that since we have the <code>data = df</code> argument after the comma, we don’t need to include <code>df$</code> before the two variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="do">## t-test of difference in math scores across parental education (BA/BA or not)</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(bynels2m <span class="sc">~</span> par_ba, <span class="at">data =</span> df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  bynels2m by par_ba
t = -38.341, df = 13269, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -8.671327 -7.827819
sample estimates:
mean in group 0 mean in group 1 
       41.97543        50.22501 </code></pre>
</div>
</div>
<p>Looking at the bottom of the output, we see the mean math scores across the two groups:</p>
<ul>
<li>Math score of <code>41.9754334</code> for students for whom neither parent has a Bachelor’s degree or higher</li>
<li>Math score of <code>50.2250064</code> for students for whom at least one parent has a Bachelor’s degree or higher</li>
</ul>
<p>Are these differences statistically meaningful? Looking in the third line, we see a large t stat of <code>-38.34</code> which is highly statistically significant at conventional levels. Taken together, we can say that among this sample of students, those from households in which at least one parent had a Bachelor’s degree or higher tended to score higher on the math exam than their peers whose parents did not have a Bachelor’s degree or higher. Furthermore, this result is <em>statistically significant</em>, meaning that we can reject the null that there is no difference between the groups, that is, the difference we observe is just sampling noise.</p>
<p>Is the difference <em>practically significant</em>? Maybe, but to really know that we need to understand more about the design and scaling of the math test. Once we do, we can apply our content-area knowledge and place our findings in their proper context.</p>
<blockquote class="blockquote">
<h4 id="quick-exercise-1">Quick exercise</h4>
<p>Run a t-test of reading scores against whether the father has a Bachelor’s degree (<code>fath_ba</code>).</p>
</blockquote>
</section>
<section id="using-survey-weights" class="level2">
<h2 data-anchor-id="using-survey-weights">Using survey weights</h2>
<p>So far we haven’t used survey weights, but they are very important if we want to make population-level inferences using surveys with complex sampling designs. Yes, we can produce means, compute t-tests, and fit regressions without weights, but our results may not be externally valid due the fact that observations in our sample are almost certainly out of proportion to their occurrence in the population. Otherwise stated, it’s likely that our sample under-represents some groups while over-representing others. The upshot is that any unweighted estimates will be a function of what we observe (sample) and not necessarily what we want (population). Furthermore, our standard errors — which we use when determining statistical significance — may be incorrect if we don’t use survey weights, meaning that we may be more likely to commit Type I or Type II errors.</p>
<p>So that we can make population-level inferences, survey designers often include weights that allow us to adjust the amount each observation contributes to our estimates. With this adjustment our estimate should better reflect the population value. To use survey weights, you’ll need to use the survey package (which we’ve already loaded above).</p>
<p>As a first step, you need to set the survey design using the <code>svydesign()</code> function. You could do this in the <code>svymean()</code> or <code>svyglm()</code> functions we’ll use to actually produce our weighted estimates, but it’s easier and clearer to do it first, store it in an object, and then re-use that object.</p>
<p><a href="https://nces.ed.gov/training/datauser/ELS_04.html">ELS has a complex sampling design that we won’t get into</a>, but the appropriate columns from our data frame, <code>df</code>, are set to the proper arguments in <code>svydesign()</code>:</p>
<ul>
<li><code>ids</code> are the primary sampling units or <code>psu</code>s<br>
</li>
<li><code>strata</code> are indicated by the <code>strat_id</code>s<br>
</li>
<li><code>weight</code> is the base-year student weight or <code>bystuwt</code></li>
<li><code>data</code> is our data frame object, <code>df</code></li>
<li><code>nest = TRUE</code> because the <code>psu</code>s are nested in <code>strat_id</code>s</li>
</ul>
<p>Finally, notice the <code>~</code> before each column name, which is necessary in this function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="do">## subset data</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>svy_df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(psu,                         <span class="co"># primary sampling unit</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>           strat_id,                    <span class="co"># stratum ID</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>           bystuwt,                     <span class="co"># weight we want to use</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>           bynels2m,                    <span class="co"># variables we want...</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>           moth_ba,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>           fath_ba,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>           par_ba,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>           byses1,</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>           lowinc,</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>           female) <span class="sc">%&gt;%</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    <span class="do">## go ahead and drop observations with missing values</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">drop_na</span>()</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a><span class="do">## set svy design data</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>svy_df <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">ids =</span> <span class="sc">~</span>psu,</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>                    <span class="at">strata =</span> <span class="sc">~</span>strat_id,</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>                    <span class="at">weight =</span> <span class="sc">~</span>bystuwt,</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> svy_df,</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>                    <span class="at">nest =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that we’ve set the survey design, let’s compare the unweighted mean with one that accounts for the survey design.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="do">## compare unweighted and survey-weighted mean of math scores</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">bynels2m_m =</span> <span class="fu">mean</span>(bynels2m, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  bynels2m_m
       &lt;dbl&gt;
1       45.4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>bynels2m, <span class="at">design =</span> svy_df, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           mean    SE
bynels2m 44.424 0.262</code></pre>
</div>
</div>
<p>It’s a little different!</p>
<p>We can also use the survey package to properly weight our t-tests and regression models — again, using the object <code>svy_df</code> in the <code>design</code> argument in place of our unset <code>df</code> data frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="do">## get svymeans by group</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">svyby</span>(<span class="sc">~</span>bynels2m, <span class="at">by =</span> <span class="sc">~</span>par_ba, <span class="at">design =</span> svy_df, <span class="at">FUN =</span> svymean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  par_ba bynels2m        se
0      0 41.43669 0.2481650
1      1 49.35088 0.3370024</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="do">## t-test using survey design / weights</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">svyttest</span>(bynels2m <span class="sc">~</span> par_ba, <span class="at">design =</span> svy_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Design-based t-test

data:  bynels2m ~ par_ba
t = 22.988, df = 389, p-value &lt; 2.2e-16
alternative hypothesis: true difference in mean is not equal to 0
95 percent confidence interval:
 7.237325 8.591066
sample estimates:
difference in mean 
          7.914195 </code></pre>
</div>
</div>
<p>Notice that unlike the base R <code>t.test()</code> function, <code>svyttest()</code> gives the difference between the groups. That’s part of the reason we began by using <code>svyby()</code> function with <code>FUN = svymean</code>. Looking at the full output between the two functions, our results are a little different from what we got earlier without weights.</p>
<blockquote class="blockquote">
<h4 id="quick-exercise-2">QUICK EXERCISE</h4>
<p>Compare this to the output from <code>t.test()</code> above. How is it different?</p>
</blockquote>
<p>Two notes:</p>
<p>First, the <strong>survey</strong> library has a ton of features and is worth diving into if you regularly work with survey data. We’ve only scratched the surface of what it can do. But keep in mind that whatever statistical test you want to perform, there’s likely a version that works with survey weights via this library.</p>
<p>Second, you’ll have to spend <strong>a lot</strong> of time reading the survey methodology documents in order to understand which weights you should you use (context always matters) so that you can properly set up your survey design with <code>svydesign()</code>. But be warned: even then it won’t always be clear which weights are the “correct” weights. That said, do as you always do: (1) your due diligence, and (2) be prepared to defend your choice as well as note potential limitations.</p>
<p>In this lesson, we’ll move beyond t.tests to regression. As before, this lesson is too short to stand in for a full course on regression analyses. However, it should give you the basics of how to fit regression and store key parameters. We’ll also cover the basics of prediction and the estimate of marginal “effects” (nothing causal here!).</p>
</section>
<section id="data-1" class="level2">
<h2 data-anchor-id="data-1">Data</h2>
<p>In this lesson, we’ll use the same data from the <a href="https://nces.ed.gov/surveys/els2002/">NCES Education Longitudinal Study of 2002</a>. So you don’t have to go back to the prior lesson, here again is a codebook with descriptions of the variables included in our lesson today:</p>
<table class="table">
<colgroup>
<col style="width: 24%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">variable</th>
<th style="text-align: left;">description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">stu_id</td>
<td style="text-align: left;">student id</td>
</tr>
<tr class="even">
<td style="text-align: left;">sch_id</td>
<td style="text-align: left;">school id</td>
</tr>
<tr class="odd">
<td style="text-align: left;">strat_id</td>
<td style="text-align: left;">stratum</td>
</tr>
<tr class="even">
<td style="text-align: left;">psu</td>
<td style="text-align: left;">primary sampling unit</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bystuwt</td>
<td style="text-align: left;">student weight</td>
</tr>
<tr class="even">
<td style="text-align: left;">bysex</td>
<td style="text-align: left;">sex-composite</td>
</tr>
<tr class="odd">
<td style="text-align: left;">byrace</td>
<td style="text-align: left;">student’s race/ethnicity-composite</td>
</tr>
<tr class="even">
<td style="text-align: left;">bydob_p</td>
<td style="text-align: left;">student’s year and month of birth</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bypared</td>
<td style="text-align: left;">parents’ highest level of education</td>
</tr>
<tr class="even">
<td style="text-align: left;">bymothed</td>
<td style="text-align: left;">mother’s highest level of education-composite</td>
</tr>
<tr class="odd">
<td style="text-align: left;">byfathed</td>
<td style="text-align: left;">father’s highest level of education-composite</td>
</tr>
<tr class="even">
<td style="text-align: left;">byincome</td>
<td style="text-align: left;">total family income from all sources 2001-composite</td>
</tr>
<tr class="odd">
<td style="text-align: left;">byses1</td>
<td style="text-align: left;">socio-economic status composite, v.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">byses2</td>
<td style="text-align: left;">socio-economic status composite, v.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bystexp</td>
<td style="text-align: left;">how far in school student thinks will get-composite</td>
</tr>
<tr class="even">
<td style="text-align: left;">bynels2m</td>
<td style="text-align: left;">els-nels 1992 scale equated sophomore math score</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bynels2r</td>
<td style="text-align: left;">els-nels 1992 scale equated sophomore reading score</td>
</tr>
<tr class="even">
<td style="text-align: left;">f1qwt</td>
<td style="text-align: left;">questionnaire weight for f1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">f1pnlwt</td>
<td style="text-align: left;">panel weight, by and f1 (2002 and 2004)</td>
</tr>
<tr class="even">
<td style="text-align: left;">f1psepln</td>
<td style="text-align: left;">f1 post-secondary plans right after high school</td>
</tr>
<tr class="odd">
<td style="text-align: left;">f2ps1sec</td>
<td style="text-align: left;">Sector of first postsecondary institution</td>
</tr>
<tr class="even">
<td style="text-align: left;">female</td>
<td style="text-align: left;">== 1 if female</td>
</tr>
<tr class="odd">
<td style="text-align: left;">moth_ba</td>
<td style="text-align: left;">== 1 if mother has BA/BS</td>
</tr>
<tr class="even">
<td style="text-align: left;">fath_ba</td>
<td style="text-align: left;">== 1 if father has BA/BS</td>
</tr>
<tr class="odd">
<td style="text-align: left;">par_ba</td>
<td style="text-align: left;">== 1 if either parent has BA/BS</td>
</tr>
<tr class="even">
<td style="text-align: left;">plan_col_grad</td>
<td style="text-align: left;">== 1 if student plans to earn college degree</td>
</tr>
<tr class="odd">
<td style="text-align: left;">lowinc</td>
<td style="text-align: left;">== 1 if income &lt; $25k</td>
</tr>
</tbody>
</table>
<p>We’ll load the same libraries and data!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="do">## ---------------------------</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="do">## libraries</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="do">## ---------------------------</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="do">## ---------------------------</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="do">## input data</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="do">## ---------------------------</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="do">## assume we're running this script from the ./scripts subdirectory</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="fu">file.path</span>(<span class="st">"data"</span>, <span class="st">"els_plans.dta"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="linear-model" class="level2">
<h2 data-anchor-id="linear-model">Linear model</h2>
<p>Linear models are the go-to method of making inferences for many data analysts. In R, the <code>lm()</code> command is used to compute an <a href="https://en.wikipedia.org/wiki/Ordinary_least_squares">ordinary least squares (OLS)</a> regression. Unlike above, where we just let the <code>t.test()</code> output print to the console, we can and will store the output in an object.</p>
<p>First, let’s compute the same t-test as in the prior inferential lesson, but in a regression framework. This time, we’ll assume equal variances between the distributions in the t-test above (<code>var.equal = TRUE</code>), so we should get the same results as we did before.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="do">## t-test of difference in math scores across parental education (BA/BA or not)</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(bynels2m <span class="sc">~</span> par_ba, <span class="at">data =</span> df, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  bynels2m by par_ba
t = -38.54, df = 15234, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -8.669138 -7.830008
sample estimates:
mean in group 0 mean in group 1 
       41.97543        50.22501 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">## compute same test as above, but in a linear model</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(bynels2m <span class="sc">~</span> par_ba, <span class="at">data =</span> df)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bynels2m ~ par_ba, data = df)

Coefficients:
(Intercept)       par_ba  
      41.98         8.25  </code></pre>
</div>
</div>
<p>The output is a little thin: just the coefficients. To see the full range of information you want from regression output, use the <code>summary()</code> function wrapped around the <code>fit</code> object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="do">## use summary to see more information about regression</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bynels2m ~ par_ba, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-35.515  -9.685   0.595   9.885  37.015 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  41.9754     0.1375  305.35   &lt;2e-16 ***
par_ba        8.2496     0.2141   38.54   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 13.01 on 15234 degrees of freedom
  (924 observations deleted due to missingness)
Multiple R-squared:  0.08884,   Adjusted R-squared:  0.08878 
F-statistic:  1485 on 1 and 15234 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We’ll more fully discuss this output in the next section. For now, let’s compare the key findings to those returned from the t test.</p>
<p>Because our right-hand side (RHS) variable is an indicator variable that <code>== 0</code> for parents without a BA/BS or higher and <code>== 1</code> if either parent has a BA/BS or higher, then the intercept reflects the math test score for students when <code>par_ba == 0</code>. This matches the <code>mean in group 0</code> value from the t test above.</p>
<p>In a regression framework, the coefficient on <code>par_ba</code> is the marginal difference when <code>par_ba</code> increases by one unit. Since <code>pared</code> is the only parameter on the RHS (besides the intercept) and only takes on values 0 and 1, we can add its coefficient to the intercept to get the math test score mean for students with parents with a BA/BS or higher.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="do">## add intercept and par_ba coefficient</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>fit<span class="sc">$</span>coefficients[[<span class="st">"(Intercept)"</span>]] <span class="sc">+</span> fit<span class="sc">$</span>coefficients[[<span class="st">"par_ba"</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 50.22501</code></pre>
</div>
</div>
<p>Looks like this value matches what we saw before (within rounding). Going the other way, the coefficient on <code>par_ba</code>, <code>8.2495729</code>, is the same as the difference between the groups in the t test. Finally, notice that the absolute value of the test statistic for the t test and the <code>par_ba</code> coefficient are the same value: <code>38.54</code>. Success!</p>
<section id="multiple-regression" class="level3">
<h3 data-anchor-id="multiple-regression">Multiple regression</h3>
<p>To fit a multiple regression, use the same formula framework that we’ve use before with the addition of all the terms you want on right-hand side of the equation separated by plus (<code>+</code>) signs.</p>
<p><em><strong>NB</strong> From here on out, we’ll spend less time interpreting the regression results so that we can focus on the tools of running regressions. That said, let me know if you have questions of interpretation.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="do">## linear model with more than one covariate on the RHS</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(bynels2m <span class="sc">~</span> byses1 <span class="sc">+</span> female <span class="sc">+</span> moth_ba <span class="sc">+</span> fath_ba <span class="sc">+</span> lowinc,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> df)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bynels2m ~ byses1 + female + moth_ba + fath_ba + 
    lowinc, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-39.456  -8.775   0.432   9.110  40.921 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  45.7155     0.1811 252.420  &lt; 2e-16 ***
byses1        6.8058     0.2387  28.511  &lt; 2e-16 ***
female       -1.1483     0.1985  -5.784 7.42e-09 ***
moth_ba       0.4961     0.2892   1.715  0.08631 .  
fath_ba       0.8242     0.2903   2.840  0.00452 ** 
lowinc       -2.1425     0.2947  -7.271 3.75e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.24 on 15230 degrees of freedom
  (924 observations deleted due to missingness)
Multiple R-squared:  0.1929,    Adjusted R-squared:  0.1926 
F-statistic: 728.1 on 5 and 15230 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The full output tells you:</p>
<ul>
<li>the model that you fit, under <code>Call:</code></li>
<li>a table of coefficients with
<ul>
<li>the point estimates (<code>Estimate</code>)</li>
<li>the point estimate errors (<code>Std. Error</code>)</li>
<li>the test statistic for each point estimate (<code>t value</code> with this model)</li>
<li>the p value for each point estimate (<code>Pr(&gt;|t|)</code>)</li>
</ul></li>
<li>significance stars (<code>.</code> and <code>*</code>) along with legend</li>
<li>the R-squared values (<code>Multiple R-squared</code> and <code>Adjusted     R-squared</code>)</li>
<li>the model F-statistic (<code>F-statistic</code>)</li>
<li>number of observations dropped if any</li>
</ul>
<p>If observations were dropped due to missing values (<code>lm()</code> does this automatically by default), you can recover the number of observations actually used with the <code>nobs()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">## check number of observations</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nobs</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15236</code></pre>
</div>
</div>
<p>The <code>fit</code> object also holds a lot of other information that is sometimes useful.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="do">## see what fit object holds</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "coefficients"  "residuals"     "effects"       "rank"         
 [5] "fitted.values" "assign"        "qr"            "df.residual"  
 [9] "na.action"     "xlevels"       "call"          "terms"        
[13] "model"        </code></pre>
</div>
</div>
<p>In addition to the <code>coefficients</code>, which you pulled out of the first model, both <code>fitted.values</code> and <code>residuals</code> are stored in the object. You can access these “hidden” attributes by treating the <code>fit</code> object like a data frame and using the <code>$</code> notation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="do">## see first few fitted values and residuals</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(fit<span class="sc">$</span>fitted.values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6 
42.86583 48.51465 38.78234 36.98010 32.82855 38.43332 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(fit<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1          2          3          4          5          6 
  4.974173   6.785347  27.457659  -1.650095  -2.858552 -14.153323 </code></pre>
</div>
</div>
<blockquote class="blockquote">
<h4 id="quick-exercise-3">Quick exercise</h4>
<p>Add the fitted values to the residuals and store in an object (<code>x</code>). Compare these values to the math scores in the data frame.</p>
</blockquote>
<p>As a final note, the model matrix used fit the regression can be retrieved using <code>model.matrix()</code>. Since we have a lot of observations, we’ll just look at the first few rows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="do">## see the design matrix</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">model.matrix</span>(fit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) byses1 female moth_ba fath_ba lowinc
1           1  -0.25      1       0       0      0
2           1   0.58      1       0       0      0
3           1  -0.85      1       0       0      0
4           1  -0.80      1       0       0      1
5           1  -1.41      1       0       0      1
6           1  -1.07      0       0       0      0</code></pre>
</div>
</div>
<p>What this shows is that the fit object actually stores a copy of the data used to run it. That’s really convenient if you want to save the object to disk (with the <code>save()</code> function) so you can review the regression results later. But keep in mind that if you share that file, you are sharing the part of the data used to estimate it. Because a lot of education data is restricted in some way — via memorandums of understanding (MOUs) or IRB — be careful about sharing the saved output object. Typically you’ll only share the results in a table or figure, but just be aware.</p>
</section>
<section id="using-categorical-variables-or-factors" class="level3">
<h3 data-anchor-id="using-categorical-variables-or-factors">Using categorical variables or factors</h3>
<p>It’s not necessary to pre-construct dummy variables if you want to use a categorical variable in your model. Instead you can use the categorical variable wrapped in the <code>factor()</code> function. This tells R that the underlying variable shouldn’t be treated as a continuous value, but should be discrete groups. R will make the dummy variables on the fly when fitting the model. We’ll include the categorical variable <code>bystexp</code> in this model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="do">## check values of student expectations</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(bystexp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 2
  bystexp                                           n
  &lt;dbl+lbl&gt;                                     &lt;int&gt;
1 -1 [{don^t know}]                              1450
2  1 [less than high school graduation]           128
3  2 [high school graduation or ged only]         983
4  3 [attend or complete 2-year college/school]   879
5  4 [attend college, 4-year degree incomplete]   561
6  5 [graduate from college]                     5416
7  6 [obtain master^s degree or equivalent]      3153
8  7 [obtain phd, md, or other advanced degree]  2666
9 NA                                              924</code></pre>
</div>
</div>
<p>Even though student expectations of eventual degree attainment are roughly ordered, let’s use them in our model as discrete groups. That way we can leave in “Don’t know” and don’t have to worry about that “attend college, 4-year degree incomplete” is somehow <em>higher</em> than “attend or complete 2-year college/school”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="do">## add factors</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(bynels2m <span class="sc">~</span> byses1 <span class="sc">+</span> female <span class="sc">+</span> moth_ba <span class="sc">+</span> fath_ba</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>          <span class="sc">+</span> lowinc <span class="sc">+</span> <span class="fu">factor</span>(bystexp),</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> df)</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bynels2m ~ byses1 + female + moth_ba + fath_ba + 
    lowinc + factor(bystexp), data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-41.680  -8.267   0.541   8.423  38.696 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       42.9534     0.3366 127.603  &lt; 2e-16 ***
byses1             5.1616     0.2297  22.468  &lt; 2e-16 ***
female            -2.3828     0.1909 -12.481  &lt; 2e-16 ***
moth_ba            0.4119     0.2742   1.502   0.1331    
fath_ba            0.6250     0.2754   2.270   0.0232 *  
lowinc            -2.2017     0.2794  -7.880 3.50e-15 ***
factor(bystexp)1 -10.0569     1.0710  -9.390  &lt; 2e-16 ***
factor(bystexp)2  -5.4527     0.4813 -11.329  &lt; 2e-16 ***
factor(bystexp)3  -1.2000     0.4966  -2.416   0.0157 *  
factor(bystexp)4  -3.5317     0.5771  -6.119 9.62e-10 ***
factor(bystexp)5   3.6345     0.3446  10.546  &lt; 2e-16 ***
factor(bystexp)6   7.6366     0.3736  20.442  &lt; 2e-16 ***
factor(bystexp)7   7.5114     0.3860  19.460  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 11.6 on 15223 degrees of freedom
  (924 observations deleted due to missingness)
Multiple R-squared:  0.2754,    Adjusted R-squared:  0.2748 
F-statistic: 482.1 on 12 and 15223 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>If you’re using labeled data like we have been for the past couple of modules, you can use the <code>as_factor()</code> function from the <a href="https://haven.tidyverse.org/reference/as_factor.html">haven library</a> in place of the base <code>factor()</code> function. You’ll still see the <code>as_factor(&lt;var&gt;)</code> prefix on each coefficient, but now you’ll have labels instead of the underlying values, which should make parsing the output a little easier.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="do">## same model, but use as_factor() instead of factor() to use labels</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(bynels2m <span class="sc">~</span> byses1 <span class="sc">+</span> female <span class="sc">+</span> moth_ba <span class="sc">+</span> fath_ba</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>          <span class="sc">+</span> lowinc <span class="sc">+</span> <span class="fu">as_factor</span>(bystexp),</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> df)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bynels2m ~ byses1 + female + moth_ba + fath_ba + 
    lowinc + as_factor(bystexp), data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-41.680  -8.267   0.541   8.423  38.696 

Coefficients:
                                                           Estimate Std. Error
(Intercept)                                                 42.9534     0.3366
byses1                                                       5.1616     0.2297
female                                                      -2.3828     0.1909
moth_ba                                                      0.4119     0.2742
fath_ba                                                      0.6250     0.2754
lowinc                                                      -2.2017     0.2794
as_factor(bystexp)less than high school graduation         -10.0569     1.0710
as_factor(bystexp)high school graduation or ged only        -5.4527     0.4813
as_factor(bystexp)attend or complete 2-year college/school  -1.2000     0.4966
as_factor(bystexp)attend college, 4-year degree incomplete  -3.5317     0.5771
as_factor(bystexp)graduate from college                      3.6345     0.3446
as_factor(bystexp)obtain master^s degree or equivalent       7.6366     0.3736
as_factor(bystexp)obtain phd, md, or other advanced degree   7.5114     0.3860
                                                           t value Pr(&gt;|t|)    
(Intercept)                                                127.603  &lt; 2e-16 ***
byses1                                                      22.468  &lt; 2e-16 ***
female                                                     -12.481  &lt; 2e-16 ***
moth_ba                                                      1.502   0.1331    
fath_ba                                                      2.270   0.0232 *  
lowinc                                                      -7.880 3.50e-15 ***
as_factor(bystexp)less than high school graduation          -9.390  &lt; 2e-16 ***
as_factor(bystexp)high school graduation or ged only       -11.329  &lt; 2e-16 ***
as_factor(bystexp)attend or complete 2-year college/school  -2.416   0.0157 *  
as_factor(bystexp)attend college, 4-year degree incomplete  -6.119 9.62e-10 ***
as_factor(bystexp)graduate from college                     10.546  &lt; 2e-16 ***
as_factor(bystexp)obtain master^s degree or equivalent      20.442  &lt; 2e-16 ***
as_factor(bystexp)obtain phd, md, or other advanced degree  19.460  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 11.6 on 15223 degrees of freedom
  (924 observations deleted due to missingness)
Multiple R-squared:  0.2754,    Adjusted R-squared:  0.2748 
F-statistic: 482.1 on 12 and 15223 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>If you look at the model matrix, you can see how R created the dummy variables from <code>bystexp</code>: adding new columns of only 0/1s that correspond to the <code>bystexp</code> value of each student.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="do">## see what R did under the hood to convert categorical to dummies</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">model.matrix</span>(fit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) byses1 female moth_ba fath_ba lowinc
1           1  -0.25      1       0       0      0
2           1   0.58      1       0       0      0
3           1  -0.85      1       0       0      0
4           1  -0.80      1       0       0      1
5           1  -1.41      1       0       0      1
6           1  -1.07      0       0       0      0
  as_factor(bystexp)less than high school graduation
1                                                  0
2                                                  0
3                                                  0
4                                                  0
5                                                  0
6                                                  0
  as_factor(bystexp)high school graduation or ged only
1                                                    0
2                                                    0
3                                                    0
4                                                    0
5                                                    0
6                                                    0
  as_factor(bystexp)attend or complete 2-year college/school
1                                                          1
2                                                          0
3                                                          0
4                                                          0
5                                                          0
6                                                          0
  as_factor(bystexp)attend college, 4-year degree incomplete
1                                                          0
2                                                          0
3                                                          0
4                                                          0
5                                                          0
6                                                          1
  as_factor(bystexp)graduate from college
1                                       0
2                                       0
3                                       0
4                                       1
5                                       1
6                                       0
  as_factor(bystexp)obtain master^s degree or equivalent
1                                                      0
2                                                      0
3                                                      0
4                                                      0
5                                                      0
6                                                      0
  as_factor(bystexp)obtain phd, md, or other advanced degree
1                                                          0
2                                                          1
3                                                          0
4                                                          0
5                                                          0
6                                                          0</code></pre>
</div>
</div>
<blockquote class="blockquote">
<h4 id="quick-exercise-4">Quick exercise</h4>
<p>Add the categorical variable <code>byincome</code> to the model above. Next use <code>model.matrix()</code> to check the RHS matrix.</p>
</blockquote>
</section>
<section id="interactions" class="level3">
<h3 data-anchor-id="interactions">Interactions</h3>
<p>Add interactions to a regression using an asterisks (<code>*</code>) between the terms you want to interact. This will add both main terms and the interaction(s) between the two to the model. Any interaction terms will be labeled using the base name or factor name of each term joined by a colon (<code>:</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="do">## add interactions</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(bynels2m <span class="sc">~</span> byses1 <span class="sc">+</span> <span class="fu">factor</span>(bypared)<span class="sc">*</span>lowinc, <span class="at">data =</span> df)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bynels2m ~ byses1 + factor(bypared) * lowinc, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-38.998  -8.852   0.326   9.063  39.257 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              44.0084     0.6345  69.355  &lt; 2e-16 ***
byses1                    7.6082     0.2772  27.448  &lt; 2e-16 ***
factor(bypared)2          1.5546     0.6544   2.376 0.017533 *  
factor(bypared)3          0.6534     0.7136   0.916 0.359863    
factor(bypared)4          1.8902     0.7198   2.626 0.008646 ** 
factor(bypared)5          1.5059     0.7200   2.091 0.036501 *  
factor(bypared)6          1.4527     0.7386   1.967 0.049235 *  
factor(bypared)7          2.0044     0.8286   2.419 0.015569 *  
factor(bypared)8          0.8190     0.9239   0.887 0.375360    
lowinc                    2.0347     0.8112   2.508 0.012140 *  
factor(bypared)2:lowinc  -2.9955     0.9298  -3.222 0.001278 ** 
factor(bypared)3:lowinc  -4.0551     1.0682  -3.796 0.000147 ***
factor(bypared)4:lowinc  -4.8143     1.1126  -4.327 1.52e-05 ***
factor(bypared)5:lowinc  -4.6890     1.0947  -4.283 1.85e-05 ***
factor(bypared)6:lowinc  -4.5252     1.0556  -4.287 1.82e-05 ***
factor(bypared)7:lowinc  -7.2222     1.3796  -5.235 1.67e-07 ***
factor(bypared)8:lowinc  -9.8773     1.6110  -6.131 8.94e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.23 on 15219 degrees of freedom
  (924 observations deleted due to missingness)
Multiple R-squared:  0.1948,    Adjusted R-squared:  0.194 
F-statistic: 230.2 on 16 and 15219 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="polynomials" class="level3">
<h3 data-anchor-id="polynomials">Polynomials</h3>
<p>To add quadratic and other polynomial terms to the model, use the <code>I()</code> function, which lets you raise the term to the power you want in the regression using the caret (<code>^</code>) operator. In the model below, we add a quadratic version of the reading score to the right-hand side.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="do">## add polynomials</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(bynels2m <span class="sc">~</span> bynels2r <span class="sc">+</span> <span class="fu">I</span>(bynels2r<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> df)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bynels2m ~ bynels2r + I(bynels2r^2), data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-33.462  -5.947  -0.156   5.780  46.645 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   12.7765815  0.6241194  20.471   &lt;2e-16 ***
bynels2r       1.1197116  0.0447500  25.021   &lt;2e-16 ***
I(bynels2r^2) -0.0006246  0.0007539  -0.828    0.407    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.921 on 15881 degrees of freedom
  (276 observations deleted due to missingness)
Multiple R-squared:  0.5658,    Adjusted R-squared:  0.5657 
F-statistic: 1.035e+04 on 2 and 15881 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<blockquote class="blockquote">
<h4 id="quick-exercise-5">Quick exercise</h4>
<p>Fit a linear model with both interactions and a polynomial term. Then look at the model matrix to see what R did under the hood.</p>
</blockquote>
</section>
</section>
<section id="generalized-linear-model-for-binary-outcomes" class="level2">
<h2 data-anchor-id="generalized-linear-model-for-binary-outcomes">Generalized linear model for binary outcomes</h2>
<p>In some cases when you have binary outcomes — 0/1 — it may be appropriate to continue using regular OLS, fitting what is typically called a <a href="https://en.wikipedia.org/wiki/Linear_probability_model"><em>linear probability model</em> or LPM</a>. In those cases, just use <code>lm()</code> as you have been.</p>
<p>But in other cases, you’ll want to fit a <a href="https://en.wikipedia.org/wiki/Generalized_linear_model">generalized linear model</a>, in which case you’ll need to switch to the <code>glm()</code> function. It is set up just like <code>lm()</code>, but it has an extra argument, <code>family</code>. Set the argument to <code>binomial()</code> when your dependent variable is binary. By default, the <code>link</code> function is a <a href="https://en.wikipedia.org/wiki/Logit">logit</a> link.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="do">## logit</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(plan_col_grad <span class="sc">~</span> bynels2m <span class="sc">+</span> <span class="fu">as_factor</span>(bypared),</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df,</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">family =</span> <span class="fu">binomial</span>())</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = plan_col_grad ~ bynels2m + as_factor(bypared), 
    family = binomial(), data = df)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.6467  -0.9581   0.5211   0.7695   1.5815  

Coefficients:
                           Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)               -1.824413   0.090000 -20.271  &lt; 2e-16 ***
bynels2m                   0.056427   0.001636  34.491  &lt; 2e-16 ***
as_factor(bypared)hsged    0.042315   0.079973   0.529   0.5967    
as_factor(bypared)att2yr   0.204831   0.088837   2.306   0.0211 *  
as_factor(bypared)grad2ry  0.480828   0.092110   5.220 1.79e-07 ***
as_factor(bypared)att4yr   0.499019   0.090558   5.511 3.58e-08 ***
as_factor(bypared)grad4yr  0.754817   0.084271   8.957  &lt; 2e-16 ***
as_factor(bypared)ma       0.943558   0.101585   9.288  &lt; 2e-16 ***
as_factor(bypared)phprof   1.052006   0.121849   8.634  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 17545  on 15235  degrees of freedom
Residual deviance: 15371  on 15227  degrees of freedom
  (924 observations deleted due to missingness)
AIC: 15389

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>If you want a <a href="https://en.wikipedia.org/wiki/Probit_model">probit</a> model, just change the link to <code>probit</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="do">## probit</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(plan_col_grad <span class="sc">~</span> bynels2m <span class="sc">+</span> <span class="fu">as_factor</span>(bypared),</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df,</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"probit"</span>))</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = plan_col_grad ~ bynels2m + as_factor(bypared), 
    family = binomial(link = "probit"), data = df)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.7665  -0.9796   0.5238   0.7812   1.5517  

Coefficients:
                            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)               -1.0522131  0.0539072 -19.519  &lt; 2e-16 ***
bynels2m                   0.0326902  0.0009357  34.938  &lt; 2e-16 ***
as_factor(bypared)hsged    0.0325415  0.0488225   0.667   0.5051    
as_factor(bypared)att2yr   0.1316456  0.0539301   2.441   0.0146 *  
as_factor(bypared)grad2ry  0.2958810  0.0554114   5.340 9.31e-08 ***
as_factor(bypared)att4yr   0.3065176  0.0544813   5.626 1.84e-08 ***
as_factor(bypared)grad4yr  0.4553127  0.0505009   9.016  &lt; 2e-16 ***
as_factor(bypared)ma       0.5525198  0.0588352   9.391  &lt; 2e-16 ***
as_factor(bypared)phprof   0.6115358  0.0688820   8.878  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 17545  on 15235  degrees of freedom
Residual deviance: 15379  on 15227  degrees of freedom
  (924 observations deleted due to missingness)
AIC: 15397

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Note that the interpretation of parameters in logit and probit models differs from that in linear model with a normal / gaussian link function. For example, a one-unit change for a parameter in a logistic regression is associated with a change in <em>log odds</em> of the outcome, <span class="math display">\[
log(\frac{p}{1-p})
\]</span> , holding all other values at some fixed value (their means, for example). If this doesn’t sound particularly interpretable, it’s not! This is one reason people continue to use linear probability models (LPMs) rather than logits/probits (there are <a href="https://opa.hhs.gov/sites/default/files/2020-07/lpm-tabrief.pdf">other reasons</a> too). As always, make the choice that best fits your data, research questions, and intended audience.</p>
<blockquote class="blockquote">
<h4 id="quick-exercise-6">Quick exercise</h4>
<p>Fit a logit or probit model to another binary outcome.</p>
</blockquote>
</section>
<section id="using-survey-weights-in-a-regression" class="level2">
<h2 data-anchor-id="using-survey-weights-in-a-regression">Using survey weights in a regression</h2>
<p>We spent time in the Inferential I lesson on setting up a data frame that accounted for survey weights. Review that if need a reminder of the intuition.</p>
<p>Important for this lesson is that you can (and should!) use survey weights in a regression framework. As a reminder, here’s the information you need to set up the <code>svydesign()</code> that accounts for <a href="https://nces.ed.gov/training/datauser/ELS_04.html">ELS’s complex sampling design</a>:</p>
<ul>
<li><code>ids</code> are the primary sampling units or <code>psu</code>s<br>
</li>
<li><code>strata</code> are indicated by the <code>strat_id</code>s<br>
</li>
<li><code>weight</code> is the base-year student weight or <code>bystuwt</code></li>
<li><code>data</code> is our data frame object, <code>df</code></li>
<li><code>nest = TRUE</code> because the <code>psu</code>s are nested in <code>strat_id</code>s</li>
</ul>
<p>Before running our survey-weighted regression, we’ll once again set up our data in a new object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="do">## subset data</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>svy_df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(psu,                         <span class="co"># primary sampling unit</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>           strat_id,                    <span class="co"># stratum ID</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>           bystuwt,                     <span class="co"># weight we want to use</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>           bynels2m,                    <span class="co"># variables we want...</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>           moth_ba,</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>           fath_ba,</span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>           par_ba,</span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>           byses1,</span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>           lowinc,</span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>           female) <span class="sc">%&gt;%</span></span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a>    <span class="do">## go ahead and drop observations with missing values</span></span>
<span id="cb59-14"><a href="#cb59-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">drop_na</span>()</span>
<span id="cb59-15"><a href="#cb59-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-16"><a href="#cb59-16" aria-hidden="true" tabindex="-1"></a><span class="do">## set svy design data</span></span>
<span id="cb59-17"><a href="#cb59-17" aria-hidden="true" tabindex="-1"></a>svy_df <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">ids =</span> <span class="sc">~</span>psu,</span>
<span id="cb59-18"><a href="#cb59-18" aria-hidden="true" tabindex="-1"></a>                    <span class="at">strata =</span> <span class="sc">~</span>strat_id,</span>
<span id="cb59-19"><a href="#cb59-19" aria-hidden="true" tabindex="-1"></a>                    <span class="at">weight =</span> <span class="sc">~</span>bystuwt,</span>
<span id="cb59-20"><a href="#cb59-20" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> svy_df,</span>
<span id="cb59-21"><a href="#cb59-21" aria-hidden="true" tabindex="-1"></a>                    <span class="at">nest =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that we’ve done that, here’s how we run a weighted regression. Notice that it’s <code>svyglm()</code>, even though we used <code>lm()</code> before (the default <code>"link"</code> function in <code>glm()</code> is <code>gaussian</code> or normal; if we had binary outcomes and wanted to use a logit link then we could include <code>family = binomial()</code> as we did before).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="do">## fit the svyglm regression and show output</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>svyfit <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(bynels2m <span class="sc">~</span> byses1 <span class="sc">+</span> female <span class="sc">+</span> moth_ba <span class="sc">+</span> fath_ba <span class="sc">+</span> lowinc,</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">design =</span> svy_df)</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(svyfit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
svyglm(formula = bynels2m ~ byses1 + female + moth_ba + fath_ba + 
    lowinc, design = svy_df)

Survey design:
svydesign(ids = ~psu, strata = ~strat_id, weight = ~bystuwt, 
    data = svy_df, nest = TRUE)

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  45.2221     0.2710 166.867  &lt; 2e-16 ***
byses1        6.9470     0.2913  23.849  &lt; 2e-16 ***
female       -1.0715     0.2441  -4.389 1.47e-05 ***
moth_ba       0.6633     0.3668   1.809   0.0713 .  
fath_ba       0.5670     0.3798   1.493   0.1363    
lowinc       -2.4860     0.3644  -6.822 3.49e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 150.5809)

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>As when compared t.test results when using unweighted and weighted data, our regression results are little different when using the weights. As a reminder, there’s no single quick answer to using weights in a regression framework. It’s up to you and your investigation of the code book to decide:</p>
<ul>
<li>the appropriate weights to choose (there are usually many options!)</li>
<li>what weights mean in the context of missing data</li>
<li>what weights mean in a complex research design</li>
</ul>
<section id="predictions" class="level3">
<h3 data-anchor-id="predictions">Predictions</h3>
<p>Being able to generate predictions from new data can be a powerful tool. Above, we were able to return the predicted values from the fit object. We can also use the <code>predict()</code> function to return the standard error of the prediction in addition to the predicted values for new observations.</p>
<p>First, we’ll get predicted values using the original data along with their standard errors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="do">## predict from first model</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(bynels2m <span class="sc">~</span> byses1 <span class="sc">+</span> female <span class="sc">+</span> moth_ba <span class="sc">+</span> fath_ba <span class="sc">+</span> lowinc,</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> df)</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="do">## old data</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>fit_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a><span class="do">## show options</span></span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(fit_pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "fit"            "se.fit"         "df"             "residual.scale"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(fit_pred<span class="sc">$</span>fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6 
42.86583 48.51465 38.78234 36.98010 32.82855 38.43332 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(fit_pred<span class="sc">$</span>se.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1755431 0.2587681 0.2314676 0.2396327 0.2737971 0.2721818</code></pre>
</div>
</div>
<p>With the standard errors, we can get a better feel for how much faith we want to put in our predictions. If the standard errors are low, then maybe we feel more secure than if the errors are large. Alternatively, perhaps the errors are uniformly lower for some parts of our data than others. If so, that might suggest more investigation or a note on the limitations of our predictions for parts of the sample.</p>
<section id="two-other-types-of-predictions" class="level4">
<h4 data-anchor-id="two-other-types-of-predictions">Two other types of predictions</h4>
<p>We won’t practice these since in application they work similarly to what we did above. However, I do want to note two other types of predictions that you might want to make. Both involve making predictions for data that you didn’t use to fit your model. Predictions using new data or held-out data in a train/test framework are another way to evaluate your model. If you predict well to new/held-out data, that can be a good sign for the utility of your model.</p>
<section id="predictions-with-new-data" class="level5">
<h5 data-anchor-id="predictions-with-new-data">Predictions with new data</h5>
<p>Ideally, we would have a new observations with which to make predictions. Then we could test our modeling choices by seeing how well they predicted the outcomes of the new observations.</p>
<p>With discrete outcomes (like binary 0/1 data), for example, we could use our model and right-hand side variables from new observations to predict whether the new observation should have a 0 or 1 outcome. Then we could compare those predictions to the actual observed outcomes by making a 2 by 2 <a href="https://en.wikipedia.org/wiki/Confusion_matrix">confusion matrix</a> that counted the numbers of true positives and negatives (correct predictions) and false positives and negatives (incorrect predictions).</p>
<p>With continuous outcomes, we could follow the same procedure as above, but rather than using a confusion matrix, instead assess our model performance by measuring the error between our predictions and the observed outcomes. Depending on our problem and model, we might care about minimizing the root mean square error, the mean absolute error, or some other metric of the error.</p>
</section>
<section id="predictions-using-training-and-testing-data" class="level5">
<h5 data-anchor-id="predictions-using-training-and-testing-data">Predictions using training and testing data</h5>
<p>In the absence of new data, we instead could have separated our data into two data sets, a <a href="https://en.wikipedia.org/wiki/Training,_test,_and_validation_sets">training set and test set</a>. After fitting our model to the training data, we could have tested it by following either above procedure with the testing data (depending on the outcome type). Setting a rule for ourselves, we could evaluate how well we did, that is, how well our training data model classified test data outcomes, and perhaps decide to adjust our modeling assumptions. This is a fundamental way that many machine learning algorithm assess fit.</p>
</section>
</section>
</section>
<section id="margins" class="level3">
<h3 data-anchor-id="margins">Margins</h3>
<p>Using the <code>predict()</code> function alongside some other skills we have practiced, we can also make predictions on the margin a la Stata’s <a href="https://www.stata.com/help.cgi?margins"><code>-margins-</code> suite of commands</a>.</p>
<p>For example, after fitting our multiple regression, we might ask ourselves, what is the marginal association of coming from a family with low income on math scores, holding all other terms in our model constant? In other words, if student A and student B are similar along dimensions we can observe (let’s say the average student in our sample) except for the fact that student A’s family is considered lower income and student B’s is not, what if any test score difference might we expect?</p>
<p>To answer this question, we first need to make a “new” data frame with a column each for the variables used in the model and rows that equal the number of predictive margins that we want to create. In our example, that means making a data frame with two rows and five columns.</p>
<p>With <code>lowinc</code>, the variable that we want to make marginal predictions for, we have two potential values: 0 and 1. This is the reason our “new” data frame has two rows. If <code>lowinc</code> took on four values, for example, then our “new” data frame would have four rows, one for each potential value. But since we have two, <code>lowinc</code> in our “new” data frame will equal <code>0</code> in one row and <code>1</code> in the other row.</p>
<p>All other columns in the “new” data frame should have consistent values down their rows. Often, each column’s repeated value is the variable’s average in the data. Though we could use the original data frame (<code>df</code>) to generate these averages, the resulting values may summarize different data from what was used to fit the model if there were observations that <code>lm()</code> dropped due to missing values. That happened with our model. We could try to use the original data frame and account for dropped observations, but I think it’s easier to use the design matrix that’s retrieved from <code>model.matrix()</code>.</p>
<p>The code below goes step-by-step to make the “new” data frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="do">## create new data that has two rows, with averages and one marginal change</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="do">## (1) save model matrix</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>mm <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(fit)</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) byses1 female moth_ba fath_ba lowinc
1           1  -0.25      1       0       0      0
2           1   0.58      1       0       0      0
3           1  -0.85      1       0       0      0
4           1  -0.80      1       0       0      1
5           1  -1.41      1       0       0      1
6           1  -1.07      0       0       0      0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="do">## (2) drop intercept column of ones (predict() doesn't need them)</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>mm <span class="ot">&lt;-</span> mm[,<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  byses1 female moth_ba fath_ba lowinc
1  -0.25      1       0       0      0
2   0.58      1       0       0      0
3  -0.85      1       0       0      0
4  -0.80      1       0       0      1
5  -1.41      1       0       0      1
6  -1.07      0       0       0      0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="do">## (3) convert to data frame so we can use $ notation in next step</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>mm <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(mm)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="do">## (4) new data frame of means where only lowinc changes</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>new_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">byses1 =</span> <span class="fu">mean</span>(mm<span class="sc">$</span>byses1),</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">female =</span> <span class="fu">mean</span>(mm<span class="sc">$</span>female),</span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">moth_ba =</span> <span class="fu">mean</span>(mm<span class="sc">$</span>moth_ba),</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fath_ba =</span> <span class="fu">mean</span>(mm<span class="sc">$</span>fath_ba),</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">lowinc =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a><span class="do">## see new data</span></span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>new_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  byses1 female moth_ba fath_ba lowinc
   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
1 0.0421  0.503   0.274   0.320      0
2 0.0421  0.503   0.274   0.320      1</code></pre>
</div>
</div>
<p>Notice how the new data frame has the same terms that were used in the original model, but has only two rows. In the <code>lowinc</code> column, the values switch from <code>0</code> to <code>1</code>. All the other rows are averages of the data used to fit the model. This of course makes for a somewhat nonsensical average (what does it mean that a single father to have .32 of a BA/BS?), but that’s okay. Again, what we want right now are two students who represent the “average” student except one is low income and the other is not.</p>
<p>To generate the prediction, we use the same function call as before, but use our <code>new_df</code> object with the <code>newdata</code> argument.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="do">## predict margins</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fit, <span class="at">newdata =</span> new_df, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$fit
       1        2 
45.82426 43.68173 

$se.fit
        1         2 
0.1166453 0.2535000 

$df
[1] 15230

$residual.scale
[1] 12.24278</code></pre>
</div>
</div>
<p>Our results show that compared to otherwise similar students, those with a family income less than $25,000 a year are predicted to score about two points lower on their math test. To be clear, this is not a casual estimate, but rather associational. This means we would be wrong to say that having a lower family income <em>causes</em> lower math test scores (which doesn’t jibe with our domain knowledge either; low income is almost certainly a proxy for other omitted variables — access to educational resources for just one thing — that are much more directly linked to test scores).</p>
<p>I also want to note that we held the other covariates at their means. We could have instead chosen other values (<em>e.g.</em> <code>fath_ba == 1</code> or <code>female == 1</code>), which would have given us different marginal associations. Dropping or including other covariates likely would change our results, as well. The takeaway is that is that margins you compute are a function of your model as well as (obviously) the margin you investigate.</p>
</section>
</section>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">

</div>
</div>
</div>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://capaldi.info">M.J. Capaldi</a>
  </li>  
</ul>
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://quarto.org/docs/websites">Built with Quarto</a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ttalVlatt/EDH-7916">
      <i class="bi bi-github" role="img" aria-label="Website Code Available Here">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>