project:
  type: website
  post-render: 
    - site-attachments/Purl-R-Scripts.R
  #  - site-attachments/docx2pdf.R
  # resources:
  #   - CNAME
    
website:
  title: "EDH 7916"
  site-url: "https://capaldi.info/7916"
  description: "Course website for EDH 7916 at the University of Florida"
  image: "apple-touch-icon.png"
  favicon: "apple-touch-icon.png"
  twitter-card: true
  open-graph: true
  navbar: false
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - text: "Syllabus"
        file: "00-Syllabus.qmd"
      - section: "Getting Started"
        contents: "*Setup*" # glob search for files with Setup
      - section: "Data Wrangling"
        contents: "*Wrangling*"
      - section: "Data Visualization"
        contents: "*Viz*"
      - section: "Quarto"
        contents: "*Quarto*"
      - section: "Programming"
        contents: "*Program*"
      - section: "Philosophy of Data Wrangling"
        contents: "*Philosophy*"
      - text: "Final Project"
        file: "99-Final-Project.qmd"
    collapse-level: 1

  page-footer:
    right: 
      - text: "Built with Quarto"
        href: https://quarto.org/docs/websites
      - icon: github
        aria-label: Website Code Available Here
        href: https://github.com/ttalVlatt/EDH-7916
    left:
      - text: "M.J. Capaldi"
        href: https://capaldi.info

      
format:
  html:
    theme: lux
    css: site-attachments/styles.css
    toc: false
    email-obfuscation: references
    anchor-sections: false

editor: source

