title: "EDH 7916: Contemporary Research in Higher Education"
org: edquant
course: edh7916
baseurl: "/edh7916"
description: |
  A course in quantitative research workflow for students in
  the higher education administration program at the University of Florida
repo: https://github.com/edquant/edh7916
zip: https://github.com/btskinner/edh7916/zipball/edh7916

scripts: scripts
data: data
lessons: lessons
pdf: assets/pdf
img: assets/img

# for github metadata (releases)
repository: edquant/edh7916
# don't show releases prior to this date (keep classes separated)
releasecutoff: 2022-12-01

info:
  term: Spring 2023
  location: University of Florida
  building: Norman Hall
  room: NRN 1019
  office: 2705G Norman Hall
  officehrs: "TBD"

contact:
  name: Benjamin Skinner
  title: Assistant Professor of Higher Education and Policy
  shorttitle: Assistant Professor
  school: University of Florida
  github: 
    name: btskinner
    url: https://github.com/btskinner
  url: https://www.btskinner.io
  uva_url: https://education.ufl.edu/faculty/skinner-benjamin-t/
  email: btskinner@coe.ufl.edu
  twitter: https://twitter.com/btskinner

ufl:
  url: https://education.ufl.edu/higher-education/
  logo: College-of-Education-UF.png

# misc opts

theme: jekyll-theme-minimal
syntax: default
mapstyle: light-v9
google_analytics: UA-63981025-1
mathjax: true
future: true

# files / directories to exclude when building
exclude: ["_lessons/*.Rmd", "_assignments/*.Rmd", _lessons_hold, _assignments_hold, _working, _student, README.md, kbuild.sh, Gemfile, Gemfile.lock, head.tex, _data_hold]

# collections
collections:
  lessons:
    output: true
    permalink: /:collection/:path
  assignments:
    output: true
    permalink: /:collection/:path
  supplemental:
    output: true
    permalink: /:collection/:path
  
